Repository MunchDev/EpidemicVisualiser, pull requests merged in 2020-05, with the labels that each got.

#21 Changes to GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, work-in-progress

#23 Use Mergify to automate PRs and re-classify issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .mergify.yml
Labels: low, work-in-progress

#25 Add countries
  .gitignore
  README.md
  cache/countries.json
Labels: documentation, enhancement, medium, work-in-progress

#12 Testing of the new release
  README.md
  requirements.txt
Labels: high, testing, work-in-progress

#26 Next release candidate cycle (Version 1.1.0)
  .gitignore
  README.md
  cache/countries.json
  requirements.txt
Labels: documentation, enhancement, high, work-in-progress

#30 Implement console application
  src/console_application.py
Labels: enhancement, high, work-in-progress
